name             'code_generator'
maintainer       'Cinc Project'
maintainer_email 'maintainers@cinc.sh'
license          'Apache-2.0'
description      'Generates Cinc code for Cinc CLI'
version          '0.1.0'
chef_version     '>= 16.0'
